### PR TITLE
Resolve #436 'I want to get the raw binary data from response.body' issue.

### LINKED ISSUE #436: I want to get the raw binary data from response.body
I need download an excel file using frisby. Frisby can request the resource but can't return the raw binary data. We can only get the decoded data, like utf-8 data. We can encode the data and then decode it to base64 and then write the data to an excel file in the disk. If we do it like this, we yet can't open the excel file as it's not under good shape.
I tried get another local excel file while using readStream.on('data', function(chunk)) method and chunk is the raw binary data and I can decode/encode it to base64 directly and write to an new excel file successfully and open it normally. 
I wonder we can get the response stream directly, I failed to get response stream and compose an excel file out, any help? I have to use 'request' method alternative but have a very bad mood on resolving this issue because of time cost. Hope some guys helping me.

### PR DESCRIPTION
**Pull request by H1Gdev**
Resolve #436 issue.

- Add rawBody (default: false)
- If rawBody is true, response.body is raw buffer (ArrayBuffer).

### CODE REVIEW

File: src/frisby/spec.js [hunk 1]
```diff
@@ -128,20 +130,29 @@ class FrisbySpec {
...
-            response._json = JSON.parse(responseBody);
-          } catch(e) {
-            return Promise.reject(new TypeError(`Invalid json response body: '${responseBody}' at ${this._request.url} reason: '${e.message}'`));
-          }
+        if (this._setupDefaults.request && this._setupDefaults.request.rawBody) {
+          return response.arrayBuffer()
+            .then(buffer => {
+              this._response._body = buffer;
+            });
+        } else {
```
Comment (vlucas) [inline src/frisby/spec.js]: Probably don't need the `else` here - this will be the default response to send when there are no special conditions.

**Comment by vlucas** [comment]
This has been released in version `v2.1.0`.
